"""Constants for the Weishaupt WCM-COM integration."""

DOMAIN = 'weishaupt_wcm_com'
NAME_PREFIX = "Weishaupt "

OIL_CONSUMPTION_KEY = "Oil Meter"
OUTSIDE_TEMPERATURE_KEY = "Outside Temperature"
LOAD_SETTING_KEY = "Load Setting"
WARM_WATER_TEMPERATURE_KEY = "Warm Water Temperature" 
FLOW_TEMPERATURE_KEY = "Flow Temperature"
FLUE_GAS_TEMPERATURE_KEY = "Flue Gas Temperature"
MIXED_EXTERNAL_TEMPERATURE_KEY = "Mixed External Temperature"
ROOM_TEMPERATURE_KEY = "Room Temperature"
OPERATING_MODE_KEY = "Operating Mode"
OPERATING_PHASE_KEY = "Operating Phase"
PUMP_KEY = "Pump"
WARM_WATER_KEY = "Warm Water"
FLAME_KEY = "Flame"
ERROR_KEY = "Error"
GAS_VALVE_1_KEY = "Gas Valve 1"
GAS_VALVE_2_KEY = "Gas Valve 2"
HEATING_KEY = "Heating"